[package]
name = "oliv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_float_eq = "1.1.3"
env_logger = "0.11.3"
png = "0.17.13"
rayon = "1.10.0"

